import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import ClientLayout from "@/components/common/ClientLayout";
import "antd/dist/reset.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Management Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <QueryProvider>
          <AntdRegistry>
            <ClientLayout>{children}</ClientLayout>
          </AntdRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
